title: DS1002
description: Programming for Data Science
theme: just-the-docs
color_scheme: light

url: https://nmagee.github.io/ds1002/

nav_external_links:
  - title: Canvas for DS1002
    url: https://canvas.its.virginia.edu/courses/78571
  - title: Google Colab
    url: https://colab.research.google.com/

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

ga-tracking: G-GWYLT2MS9Z

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

enable_copy_code_button: true

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
