title: DS1002 Programming for Data Science
description: Learn the fundamentals of data science development.
Just the Docs theme!
theme: just-the-docs

url: https://nmagee.github.io/ds1002

aux_links:
  Template Repository: https://github.com/nmagee/ds1002
